---
title: ಕನ್ನಡ ಗಾದೆಗಳ fortune cookies
tags: ಕನ್ನಡ,ಗಾದೆಗಳು,fortune,cookies,kannadablog
summary: ಈ ಹಿಂದೆ ಲಿನಕ್ಸ್ ನ fortune ತಂತ್ರಾಂಶದ ಬಗ್ಗೆ ಬರೆದಿದ್ದೆ. ಆ ಸಮಯದಲ್ಲಿ terminal ನಲ್ಲಿ ಕನ್ನಡ ಸರಿಯಾಗಿ ಬರುತ್ತಿರಲಿಲ್ಲವಾದ್ದರಿಂದ ಕನ್ನಡದ fortune cookies ನ ಮಾಡುವ ಬಗ್ಗೆ ಹೆಚ್ಚಿನ ಗಮನಹರಿಸಿರಲಿಲ್ಲ.
---

ಈ ಹಿಂದೆ ಲಿನಕ್ಸ್ ನ fortune ತಂತ್ರಾಂಶದ ಬಗ್ಗೆ ಬರೆದಿದ್ದೆ(http://aravindavk.in/blog/creating-kannada-fortune-database-for-gnu-linux/[ಇಲ್ಲಿ ನೋಡಿ]). ಆ ಸಮಯದಲ್ಲಿ terminal ನಲ್ಲಿ ಕನ್ನಡ ಸರಿಯಾಗಿ ಬರುತ್ತಿರಲಿಲ್ಲವಾದ್ದರಿಂದ ಕನ್ನಡದ fortune cookies ನ ಮಾಡುವ ಬಗ್ಗೆ ಹೆಚ್ಚಿನ ಗಮನಹರಿಸಿರಲಿಲ್ಲ. ಇತ್ತೀಚೆಗೆ KDE Konsole ನಲ್ಲಿ ಕನ್ನಡ ಬರುತ್ತೆ ಅಂತ ತಿಳಿದಾಗ ಖುಷಿಯಾಗಿತ್ತು.

ಗಾದೆಗಳಿಗೆ ಒಂದು ವೆಬ್ ಸೈಟ್ ಮಾಡೋಣ ಅಂತ ನಿನ್ನೆ ಅನ್ನಿಸಿತ್ತು, ಆದರೆ ವೆಬ್ ಸೈಟ್ ಮಾಡುವ ಹಾಗೂ ಅದನ್ನು ನೋಡಿಕೊಳ್ಳುವ ಕಷ್ಟದ ಬಗ್ಗೆ ಯೋಚಿಸುತ್ತಿದ್ದಾಗ http://copyninja.info/[ವಾಸುದೇವ್] fortune cookies ಮಾಡ್ಬೋದಲ್ವಾ ಅಂದ. ಹೇಗಿದ್ರೂ Konsole ಅಲ್ಲಿ ಕನ್ನಡ ಬರುತ್ತೆ fortune cookies ನೇ ಮಾಡೋಣ ಅನ್ನಿಸಿತು.

github ನಲ್ಲಿ https://github.com/aravindavk/fortunes-kn-gaadegalu[fortunes-kn-gaadegalu] ಅಂತ ಒಂದು project ಪ್ರಾರಂಭಿಸಿದ್ದೇನೆ, ನಿಮ್ಮ github account ಇದ್ದರೆ ಈ ಪ್ರಾಜೆಕ್ಟ್ ನ ಕ್ಲೋನ್ ಮಾಡಿಕೊಂಡು ಗಾದೆಗಳನ್ನು ಬದಲಾಯಿಸಿ/ಸೇರಿಸಿ pull request/patch ಕಳಿಸಬಹುದು. ಹೀಗೆ ಸಂಗ್ರಹಿಸಿದ ಗಾದೆಗಳನ್ನು ಯಾರು ಬೇಕಾದರೂ ಮುಕ್ತವಾಗಿ ಬಳಸಬಹುದು. (http://creativecommons.org/licenses/by-nc/3.0/deed.en_US[CC BY-NC] ಲೈಸೆನ್ಸ್ ನೊಂದಿಗೆ). ನಿಮ್ಮ github ಅಕೌಂಟ್ ಇಲ್ಲದಿದ್ದರೆ ಗಾದೆಗಳನ್ನು ಬರೆದು ನನಗೆ ಈಮೈಲ್ ಕಳುಹಿಸಬಹುದು (root@ ನನ್ನ ವೆಬ್ಸೈಟ್ ಹೆಸರು).

ಒಂದು ಸಲ ಗಾದೆಗಳು ಸಂಗ್ರಹವಾದ ನಂತರ fortune ಜೊತೆ ಅಥವಾ ತಮ್ಮ ಅಂತರ್ಜಾಲ ಪುಟಗಳಲ್ಲಿ ಬಳಸಬಹುದು. (http://www.prasannasp.net/[ಪ್ರಸನ್ನ] ಮಂಕುತಿಮ್ಮನ ಕಗ್ಗಕ್ಕೆ ಮಾಡಿದ http://wordpress.org/extend/plugins/kagga/[wordpress plugin] ನಂತೆ ಗಾದೆಗಳಿಗೂ plugin ಮಾಡಬಹುದು.)

ಗಾದೆಗಳನ್ನು ಸೇರಿಸುವಾಗ ಒಂದು ಗಾದೆಯನ್ನ ಒಂದೇ ಲೈನ್ ನಲ್ಲಿ ಬರೆಯಿರಿ. ಉದಾಹರಣೆಗೆ, 

[source,text]
----
ವೇದ ಸುಳ್ಳಾದರೂ ಗಾದೆ ಸುಳ್ಳಲ್ಲ.
ಹಾಸಿಗೆ ಇದ್ದಷ್ಟು ಕಾಲು ಚಾಚು.
----

ಅದರಲ್ಲಿರುವ ಗಾದೆಗಳನ್ನ ಬೇರೆ ಬೇರೆ format ಗೆ ಬದಲಾಯಿಸಿಕೊಳ್ಳಬಹುದು, ಈಗಿನಂತೆ fortune, PHP array ಮತ್ತು JSON format ಗೆ ಬದಲಾಯಿಸಿಕೊಳ್ಳಬಹುದಾಗಿದೆ. (https://github.com/aravindavk/fortunes-kn-gaadegalu/blob/master/README.md[ಇಲ್ಲಿ] ನೋಡಿ.)
